# Generated by Django 5.0.4 on 2025-11-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResumenGral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('idsocio', models.AutoField(primary_key=True, serialize=False)),
                ('socio', models.CharField(max_length=10, verbose_name='Socio')),
                ('porcentaje', models.FloatField(verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': 'socios',
                'db_table': 'socio',
                'ordering': ['-porcentaje'],
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('idreparto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('importe', models.FloatField(default=0, verbose_name='Importe')),
                ('cot_usd_ofi', models.FloatField(default=0, verbose_name='Cotización U$S oficial')),
                ('cot_usd_par', models.FloatField(default=0, verbose_name='Cotización U$S blue')),
                ('cuota', models.FloatField(default=0, verbose_name='Cuota de participación Reparto')),
                ('idcrianza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResumenGral.crianza', verbose_name='Crianza')),
            ],
            options={
                'verbose_name': 'reparto',
                'verbose_name_plural': 'repartos',
                'db_table': 'reparto',
                'ordering': ['-idcrianza'],
            },
        ),
    ]
