# Generated by Django 5.0.4 on 2025-11-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResumenGral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('idcrianza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ResumenGral.crianza', verbose_name='Crianza')),
                ('m3_medidor', models.IntegerField(verbose_name='M3 del medidor')),
                ('m3_9300_cal', models.FloatField(default=0, verbose_name='M3 de 9300 calorías')),
                ('total_pesos', models.FloatField(default=0, verbose_name='Total pesos crianza')),
                ('cot_usd_par', models.FloatField(default=0, verbose_name='Cotización U$S blue')),
            ],
            options={
                'verbose_name': 'gas',
                'verbose_name_plural': 'gas',
                'db_table': 'gas',
                'ordering': ['idcrianza'],
            },
        ),
    ]
