# Generated by Django 5.0.4 on 2025-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianza',
            fields=[
                ('idcrianza', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Crianza')),
                ('temporada', models.CharField(blank=True, choices=[('I', 'Invierno'), ('V', 'Verano'), ('O', 'Otoño/Prim.')], max_length=1, null=True, verbose_name='Temporada')),
                ('fechainicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechadesde', models.DateField(verbose_name='Fecha Desde')),
                ('fechahasta', models.DateField(verbose_name='Fecha Hasta')),
                ('metros2', models.IntegerField(verbose_name='M2')),
                ('ingresado', models.IntegerField(verbose_name='Total Ingresado')),
                ('dias', models.FloatField(max_length=4, verbose_name='Duración')),
                ('kgsalimento', models.IntegerField(verbose_name='kgs Alimento Consumido')),
                ('faenado', models.IntegerField(verbose_name='Total Faenado')),
                ('kgsfaenados', models.IntegerField(verbose_name='kgs Faenados')),
                ('muertosfaena', models.IntegerField(verbose_name='Muertos en Faena')),
                ('muertosgranja', models.IntegerField(verbose_name='Muertos en Granja')),
                ('granjero', models.CharField(max_length=20, verbose_name='Granjero')),
                ('fechafactura', models.DateField(blank=True, null=True, verbose_name='Fecha Factura')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ResumenGral', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'crianza',
                'verbose_name_plural': 'crianzas',
                'db_table': 'crianza',
                'ordering': ['-idcrianza'],
            },
        ),
    ]
