# Generated by Django 5.0.4 on 2026-03-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumenGral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDeCrianza',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('galpon', models.IntegerField(verbose_name='Galpón')),
                ('fechadesdepromedio', models.DateField(verbose_name='Fecha Desde Promedio')),
                ('ingresado', models.IntegerField(verbose_name='Neto Ingresado')),
                ('fechahastapromedio', models.DateField(verbose_name='Fecha Hasta Promedio')),
                ('faenado', models.IntegerField(verbose_name='Faenado')),
                ('pollosxmetro2', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Pollos por m2')),
                ('dias', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Edad')),
                ('totalagua', models.IntegerField(default=0, verbose_name='lts de Agua Consumida')),
                ('kgsalimento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='kgs de Alimento Consumido')),
                ('kgsfaenados', models.IntegerField(verbose_name='kgs Faenado')),
                ('muertosgranja', models.IntegerField(verbose_name='Muertos en Granja')),
                ('muertosfaena', models.IntegerField(verbose_name='Muertos en Faena')),
                ('crianza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResumenGral.crianza', verbose_name='Crianza')),
            ],
            options={
                'verbose_name': 'detalle de crianza',
                'verbose_name_plural': 'detalle de crianzas',
                'db_table': 'detalledecrianza',
                'ordering': ['-crianza', 'galpon'],
            },
        ),
    ]
