# Generated by Django 5.0.4 on 2026-03-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumenGral', '0002_detalledecrianza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledecrianza',
            name='totalagua',
        ),
    ]
