# Generated by Django 5.0.4 on 2025-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Cuenta')),
                ('cuenta', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'cuenta',
                'ordering': ['idcuenta'],
            },
        ),
    ]
