# Generated by Django 5.0.4 on 2025-11-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContable',
            fields=[
                ('periodo', models.CharField(max_length=6, verbose_name='Período')),
                ('naturaleza', models.IntegerField(choices=[(0, 'Eectivo'), (2, 'Tarjeta de Crédito'), (4, 'BAPRO')], verbose_name='Naturaleza')),
                ('transaccion', models.IntegerField(verbose_name='Transacción')),
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('aplicadesde', models.DateField(verbose_name='Fecha Desde')),
                ('aplicahasta', models.DateField(verbose_name='Fecha Hasta')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
                ('cot_usd_par', models.FloatField(default=0, verbose_name='Cotización U$S')),
                ('idcuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'registrocontable',
                'verbose_name_plural': 'registroscontable',
                'db_table': 'registrocontable',
                'ordering': ['-periodo', 'naturaleza', 'transaccion', 'idregistro'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrocontable',
            constraint=models.UniqueConstraint(fields=('periodo', 'naturaleza', 'transaccion', 'idregistro'), name='registro_contable_unico'),
        ),
    ]
