# Generated by Django 5.0.4 on 2025-11-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Repartos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('idaporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('importe', models.FloatField(default=0, verbose_name='Importe')),
                ('moneda', models.CharField(choices=[('D', 'U$S'), ('P', '$')], default='P', max_length=1, verbose_name='Moneda')),
                ('cot_usd_ofi', models.FloatField(default=0, verbose_name='U$S oficial')),
                ('cot_usd_par', models.FloatField(default=0, verbose_name='U$S blue')),
                ('idsocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repartos.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'aporte',
                'verbose_name_plural': 'aportes',
                'db_table': 'aporte',
                'ordering': ['-fecha'],
            },
        ),
    ]
