# Generated by Django 5.0.4 on 2025-11-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResumenGral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricidad',
            fields=[
                ('idcrianza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ResumenGral.crianza', verbose_name='Crianza')),
                ('activa_kwxh', models.FloatField(verbose_name='Energía Activa-Kw x H ')),
                ('reactiva_kvar', models.FloatField(blank=True, default=0, null=True, verbose_name='Energía ReActiva-Kvar')),
                ('perdida_kw', models.IntegerField(verbose_name='Pérdida en Kw')),
                ('total_pesos', models.FloatField(default=0, verbose_name='Total pesos crianza')),
                ('cot_usd_par', models.FloatField(default=0, verbose_name='Cotización U$S blue')),
            ],
            options={
                'verbose_name': 'electricidad',
                'verbose_name_plural': 'electricidad',
                'db_table': 'electricidad',
                'ordering': ['idcrianza'],
            },
        ),
    ]
